language: python
python:
  - '3.6'
install:
  - pip install pipenv
  - pipenv install --dev
  - >-
    curl -H 'Cache-Control: no-cache'
    https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo
    bash
addons:
  sauce_connect: true
script:
  - >-
    pipenv run coverage run --branch --source=. --omit=*/migrations/*
    ./manage.py test - pipenv run coverage xml
  - pipenv run mypy .
after_success:
  - pipenv run coveralls
  - pipenv run codecov
  - pipenv run python-codacy-coverage -r coverage.xml
  - fossa
