language: python
python:
  - '3.7-dev'
install:
  - pip install pipenv
  - pipenv install --dev
  - >-
    curl -H 'Cache-Control: no-cache'
    https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo
    bash
addons:
  sauce_connect: true
script:
  - pipenv run coverage run --branch --source="." manage.py test
  - pipenv run coverage xml
  - pipenv run mypy -p base -p riddles
  - pipenv run flake8
after_success:
  - pipenv run codecov
  - pipenv run coveralls
  - pipenv run python-codacy-coverage -r coverage.xml
  - fossa
