language: python

python:
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
#  - python manage.py test
#  - python setup.py -q install

addons:
  sauce_connect: true

# command to run tests
script: nosetests
