language: python

python:
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
#  - python setup.py -q install

addons:
  sauce_connect: true

# command to run tests
script: coverage python manage.py test

after_success:
  - coverage report
  - coveralls
